server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ectd-backend

  datasource:
    url: jdbc:mysql://localhost:3306/ectd_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lhzqq_1533266228
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ectd.backend.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ectd.backend.mapper: debug
    org.springframework.web: debug

